import { Foundation } from "@/libs/type";

  
  export const foundations: Foundation[] = [
    {
      _id: 1,
      img: "/foundation/1.png",
      title: "Natural Glow",
      price: 25.0,
      discountPrice: 30.0,
      category: "Liquid",
      quantity: 40,
      description: "A lightweight liquid foundation for a natural finish.",
      inStock: true,
      tags: ["liquid", "natural", "lightweight", "glow"],
    },
    {
      _id: 2,
      img: "/foundation/2.png",
      title: "Velvet Matte",
      price: 28.0,
      category: "Matte",
      quantity: 35,
      description: "A full-coverage matte foundation for a flawless look.",
      inStock: true,
      tags: ["matte", "full-coverage", "velvety", "flawless"],
    },
    {
      _id: 3,
      img: "/foundation/3.png",
      title: "Hydra Boost",
      price: 22.0,
      discountPrice: 26.0,
      category: "Hydrating",
      quantity: 50,
      description: "A hydrating foundation for dry skin.",
      inStock: true,
      tags: ["hydrating", "moisturizing", "dry skin", "smooth"],
    },
    {
      _id: 4,
      img: "/foundation/4.png",
      title: "Luminous Silk",
      price: 30.0,
      category: "Luminous",
      quantity: 20,
      description: "A radiant foundation for a luminous finish.",
      inStock: false,
      tags: ["luminous", "radiant", "silky", "smooth"],
    },
    {
      _id: 5,
      img: "/foundation/5.png",
      title: "Soft Blur",
      price: 24.0,
      category: "Blur",
      quantity: 60,
      description: "A soft-focus foundation for a photo-ready look.",
      inStock: true,
      tags: ["blur", "soft-focus", "photo-ready", "smooth"],
    },
    {
      _id: 6,
      img: "/foundation/6.png",
      title: "Matte Perfection",
      price: 26.0,
      category: "Matte",
      quantity: 45,
      description: "A long-wear matte foundation for oily skin.",
      inStock: true,
      tags: ["matte", "long-wear", "oily skin", "perfect"],
    },
    {
      _id: 7,
      img: "/foundation/7.png",
      title: "Dewy Finish",
      price: 29.0,
      category: "Dewy",
      quantity: 30,
      description: "A hydrating foundation for a dewy glow.",
      inStock: true,
      tags: ["dewy", "hydrating", "glowing", "natural"],
    },
    {
      _id: 8,
      img: "/foundation/8.png",
      title: "Silky Smooth",
      price: 27.0,
      discountPrice: 32.0,
      category: "Satin",
      quantity: 25,
      description: "A silky smooth foundation with medium coverage.",
      inStock: false,
      tags: ["satin", "silky", "medium coverage", "smooth"],
    },
    {
      _id: 9,
      img: "/foundation/9.png",
      title: "Ultra Cover",
      price: 35.0,
      category: "Full Coverage",
      quantity: 15,
      description: "A heavy-duty foundation for full coverage.",
      inStock: true,
      tags: ["full-coverage", "heavy-duty", "long-lasting", "perfect"],
    },
   
  ];
  