import { Lipstick } from "@/libs/type";

  
  export const lipsticks: Lipstick[] = [
    {
      _id: 1,
      img: "/lipstick/1.png",
      title: "Scarlet Passion",
      price: 15.0,
      discountPrice: 20.0,
      category: "Matte",
      quantity: 50,
      description: "A bold scarlet red with a smooth matte finish.",
      inStock: true,
      tags: ["matte", "bold", "scarlet", "long-lasting"],
    },
    {
      _id: 2,
      img: "/lipstick/2.png",
      title: "Peach Blossom",
      price: 12.0,
      category: "Creamy",
      quantity: 40,
      description: "A soft peach shade with a creamy texture.",
      inStock: true,
      tags: ["creamy", "peach", "soft", "hydrating"],
    },
    {
      _id: 3,
      img: "/lipstick/3.png",
      title: "Ruby Sparkle",
      price: 18.0,
      discountPrice: 22.0,
      category: "Glitter",
      quantity: 30,
      description: "A vibrant ruby red with a hint of sparkle.",
      inStock: false,
      tags: ["glitter", "vibrant", "sparkling", "ruby"],
    },
    {
      _id: 4,
      img: "/lipstick/4.png",
      title: "Nude Whisper",
      price: 10.0,
      category: "Natural",
      quantity: 80,
      description: "A subtle nude shade for an everyday look.",
      inStock: true,
      tags: ["natural", "nude", "subtle", "everyday"],
    },
    {
      _id: 5,
      img: "/lipstick/5.png",
      title: "Coral Glow",
      price: 14.0,
      discountPrice: 18.0,
      category: "Satin",
      quantity: 45,
      description: "A lively coral shade with a satin finish.",
      inStock: true,
      tags: ["satin", "coral", "lively", "radiant"],
    },
    {
      _id: 6,
      img: "/lipstick/6.png",
      title: "Berry Crush",
      price: 16.0,
      category: "Glossy",
      quantity: 60,
      description: "A deep berry shade with a glossy shine.",
      inStock: true,
      tags: ["glossy", "berry", "shiny", "bold"],
    },
    {
      _id: 7,
      img: "/lipstick/7.png",
      title: "Pink Charm",
      price: 13.0,
      category: "Creamy",
      quantity: 70,
      description: "A charming pink hue with a creamy texture.",
      inStock: true,
      tags: ["creamy", "pink", "charming", "smooth"],
    },
    {
      _id: 8,
      img: "/lipstick/8.png",
      title: "Plum Desire",
      price: 19.0,
      category: "Matte",
      quantity: 35,
      description: "A rich plum shade with a velvety matte finish.",
      inStock: false,
      tags: ["matte", "plum", "velvety", "rich"],
    },
    {
      _id: 9,
      img: "/lipstick/9.png",
      title: "Orange Zest",
      price: 11.0,
      discountPrice: 14.0,
      category: "Satin",
      quantity: 55,
      description: "A zesty orange shade for bold looks.",
      inStock: true,
      tags: ["satin", "orange", "zesty", "bold"],
    },
   
  ];
  