import { Perfume } from "@/libs/type";

  
  export const perfumes: Perfume[] = [
    {
      _id: 1,
      img: "/perfume/1.png",
      title: "Blush Petal",
      price: 38.0,
      discountPrice: 45.0,
      category: "Floral",
      quantity: 100,
      description: "A light and airy fragrance with hints of fresh petals.",
      inStock: true,
      tags: ["floral", "light", "airy", "petals"],
    },
    {
      _id: 2,
      img: "/perfume/2.png",
      title: "Mocha Veil",
      price: 28.0,
      category: "Woody",
      quantity: 50,
      description: "A warm blend of coffee and vanilla for cozy evenings.",
      inStock: true,
      tags: ["woody", "coffee", "vanilla", "warm"],
    },
    {
      _id: 3,
      img: "/perfume/3.png",
      title: "Citrine Dawn",
      price: 21.0,
      discountPrice: 45.0,
      category: "Citrus",
      quantity: 80,
      description: "A zesty citrus scent to start your day right.",
      inStock: true,
      tags: ["citrus", "zesty", "refreshing", "energizing"],
    },
    {
      _id: 4,
      img: "/perfume/4.png",
      title: "Mystic Amber",
      price: 45.0,
      category: "Oriental",
      quantity: 30,
      description: "An enchanting amber fragrance with exotic undertones.",
      inStock: false,
      tags: ["amber", "oriental", "exotic", "enchanting"],
    },
    {
      _id: 5,
      img: "/perfume/5.png",
      title: "Sunrise Whisper",
      price: 23.0,
      discountPrice: 45.0,
      category: "Fresh",
      quantity: 75,
      description: "A breezy fresh scent reminiscent of a sunrise.",
      inStock: true,
      tags: ["fresh", "breezy", "sunrise", "light"],
    },
    {
      _id: 6,
      img: "/perfume/6.png",
      title: "Scarlet Ember",
      price: 43.0,
      category: "Spicy",
      quantity: 60,
      description: "A bold and fiery perfume for daring spirits.",
      inStock: true,
      tags: ["spicy", "bold", "fiery", "daring"],
    },
    {
      _id: 7,
      img: "/perfume/7.png",
      title: "Cristal Rose",
      price: 10.0,
      category: "Floral",
      quantity: 120,
      description: "A delicate rose scent for a touch of elegance.",
      inStock: true,
      tags: ["floral", "rose", "elegant", "delicate"],
    },
    {
      _id: 8,
      img: "/perfume/8.png",
      title: "Golden Nectar",
      price: 25.0,
      category: "Sweet",
      quantity: 40,
      description: "A rich honey-like fragrance for golden moments.",
      inStock: false,
      tags: ["sweet", "honey", "rich", "golden"],
    },
    {
      _id: 9,
      img: "/perfume/9.png",
      title: "Midnight Ocean",
      price: 12.0,
      category: "Aquatic",
      quantity: 90,
      description: "A cool and refreshing scent inspired by the ocean.",
      inStock: true,
      tags: ["aquatic", "ocean", "cool", "refreshing"],
    },
    {
      _id: 10,
      img: "/perfume/10.png",
      title: "Rose Enigma",
      price: 45.0,
      category: "Floral",
      quantity: 35,
      description: "An intense rose fragrance with a mysterious twist.",
      inStock: true,
      tags: ["floral", "rose", "mysterious", "intense"],
    },
  ];
  